# Generated by Django 4.1.2 on 2022-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Список дилерских центров 📑',
                'verbose_name_plural': 'Списки дилерских центров 📑',
                'ordering': ['id'],
            },
        ),
    ]
