# Generated by Django 4.1.2 on 2022-10-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_address_list_loc1_list_loc2_list_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория автомобиля',
                'verbose_name_plural': 'Категории автомобилей',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['id'], 'verbose_name': 'Список дилерских центров 📑', 'verbose_name_plural': 'Список дилерских центров 📑'},
        ),
        migrations.RemoveField(
            model_name='list',
            name='address',
        ),
        migrations.RemoveField(
            model_name='list',
            name='loc1',
        ),
        migrations.RemoveField(
            model_name='list',
            name='loc2',
        ),
        migrations.RemoveField(
            model_name='list',
            name='number',
        ),
        migrations.AddField(
            model_name='list',
            name='region',
            field=models.TextField(default='0000000', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.TextField(verbose_name='Полная информация о компании'),
        ),
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_info', models.TextField(verbose_name='Информация о автомобиле')),
                ('type_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='list.categorycars', verbose_name='Тип автомобиля')),
            ],
            options={
                'verbose_name': 'Список продукции компании 🗂',
                'verbose_name_plural': 'Список продукции компании 🗂',
            },
        ),
    ]
