# Generated by Django 4.1.2 on 2022-10-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_categorycars_alter_list_options_remove_list_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='type_car2',
            field=models.TextField(default=1, verbose_name='Тип автомобиля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='region',
            field=models.TextField(default='Укажите регион!', verbose_name='Регион'),
        ),
    ]
