# Generated by Django 4.1.2 on 2022-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_carlist_type_car2_alter_list_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='quantity',
            field=models.TextField(default=1, verbose_name='Кол-во автомобилей'),
            preserve_default=False,
        ),
    ]
