# Generated by Django 4.1.2 on 2022-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_carlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('post', models.TextField(verbose_name='Новая акция')),
            ],
            options={
                'verbose_name': 'Акции компании',
                'ordering': ['id'],
            },
        ),
    ]
