# Generated by Django 4.1.2 on 2022-10-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_stockscompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockscompany',
            options={'ordering': ['id'], 'verbose_name': 'Акция от компании', 'verbose_name_plural': 'Акции от компании'},
        ),
    ]
