# Generated by Django 4.1.2 on 2022-10-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_alter_stockscompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dealer_company',
            field=models.TextField(default=1, verbose_name='Наименования компании'),
            preserve_default=False,
        ),
    ]
